from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

# add the general drivers.
src = Split("""
""")

src += Glob("*.c")

group = DefineGroup('keyIrd', src, depend = ['BSP_USING_KEYIRD'], CPPPATH = CPPPATH)
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
