from building import *

cwd = GetCurrentDir()
path = [cwd+'/inc']

# add the general drivers.
src = Split("""
fal_port.c
inc/fal_cfg.h
""")

#src  += Glob('*.c')

if  GetDepend('BSP_USING_FAL_SAMPLE'):
  src += ['sample/fal_sample.c']

if  GetDepend('BSP_USING_FM31XX'):
    src += ['fal_flash_eeprom_onrtc_port.c']

if  GetDepend('BSP_USING_EEPROM_ONCHIP'):
    src += ['fal_flash_eeprom_onchip_port.c']

if  GetDepend('BSP_USING_FLASH_ONCHIP'):
    src += ['fal_flash_lpc4088_port.c']
if  GetDepend('BSP_USING_SPFI'):
    src += ['fal_flash_extFlash_lpc4088_port.c']

# 提取当前工作目录的文件夹名称
folder_name = os.path.basename(cwd)
group = DefineGroup(folder_name, src, depend = ['RT_USING_FAL'], CPPPATH = path)

Return('group')
