# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src   = Glob('source/*.c')

CPPPATH = [cwd + '/include']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
