from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

# add the general drivers.
src = Split("""
lv_conf.h
""")

src += Glob("*.c")

group = DefineGroup('LVGL-port', src, depend = ['PKG_USING_LVGL'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
