from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""

""")

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

if GetDepend(['BSP_USING_SOFT_SPI']):
    src += ['drv_soft_spi.c']

CPPPATH = [cwd]
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
