from building import *

cwd = GetCurrentDir()
path = [cwd+'/inc']

# add the general drivers.
src = Split("""
port/ads1115_port.c
""")

src  += Glob('src/*.c')

if  GetDepend('BSP_USING_ADS1115_SHELL'):
  src += ['sample/ads1115_shell.c']
# 提取当前工作目录的文件夹名称
folder_name = os.path.basename(cwd)
group = DefineGroup(folder_name, src, depend = ['BSP_USING_ADS1115'], CPPPATH = path)

Return('group')
