import os
from building import *

group = []
cwd  = GetCurrentDir()


# add general drivers
src = Split('''
''')

src += Glob('*.c')
src += Glob('*.cpp')

path =  [cwd]



group += DefineGroup('efsm', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')

