from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

# add the general drivers.
src = Split("""
""")
port_inc = [cwd]

port_src = Glob("*.c")

group = DefineGroup('LVGL-page', port_src, depend = ['PKG_USING_LVGL'], CPPPATH = port_inc)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
