// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "ui_P00startup.h"
#include "ui_comp.h"
///////////////////// VARIABLES ////////////////////

uint32_t LV_EVENT_NOTIFY_PAGE_CHANGE;
uint32_t LV_EVENT_NOTIFY_PAGE_ACT;
uint32_t LV_EVENT_NOTIFY_UPDATE;
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    if (LV_EVENT_GET_COMP_CHILD == 0)
        LV_EVENT_GET_COMP_CHILD = lv_event_register_id();
    if (LV_EVENT_NOTIFY_PAGE_CHANGE == 0)
        LV_EVENT_NOTIFY_PAGE_CHANGE = lv_event_register_id();
    if (LV_EVENT_NOTIFY_PAGE_ACT == 0)
        LV_EVENT_NOTIFY_PAGE_ACT = lv_event_register_id();
    if (LV_EVENT_NOTIFY_UPDATE == 0)
        LV_EVENT_NOTIFY_UPDATE = lv_event_register_id();
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    lv_disp_load_scr(ui_startup_create(NULL));
}
