// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
    // SCREEN: ui_P00startup
    void ui_P00startup_screen_init(void);
    extern lv_obj_t *ui_P00startup;
    extern lv_obj_t *ui_Image1;
    extern lv_obj_t *ui_startBar;
    // SCREEN: ui_P01main
    void ui_P01main_screen_init(void);
    extern lv_obj_t *ui_P01main;
    extern lv_obj_t *ui_head;
    extern lv_obj_t *ui_title;
    extern lv_obj_t *ui_TabView1;
    extern lv_obj_t *ui_TabPage1;
    extern lv_obj_t *ui_TabPage2;
    extern lv_obj_t *ui_TextArea1;
    extern lv_obj_t *ui_TabPage3;
    extern lv_obj_t *ui_Chart1;
    extern lv_obj_t *ui_TabPage4;
    extern lv_obj_t *ui_TabPage5;
    extern lv_obj_t *ui_stateBar;
    extern lv_obj_t *ui_tips;
    extern lv_obj_t *ui_date;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_gltech_png); // assets\gltech.png

    LV_FONT_DECLARE(ui_font_heiti12);
    LV_FONT_DECLARE(ui_font_heiti16);
    LV_FONT_DECLARE(ui_font_heiti24);

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
