// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_comp.h"
#include "language.h" /*!< 多国语言管理 */

  LV_IMG_DECLARE(ui_img_gltech_png); // assets\gltech.png
  LV_FONT_DECLARE(ui_font_simfang16);
  LV_FONT_DECLARE(ui_font_simhei24);

  extern uint32_t LV_EVENT_NOTIFY_PAGE_CHANGE; /*!< page页面发生了切换 */
  extern uint32_t LV_EVENT_NOTIFY_PAGE_ACT;    /*!< page页面被激活 */
  extern uint32_t LV_EVENT_NOTIFY_UPDATE;      /*!< 通知页面刷新 */
  void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
