from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

# add the general drivers.
src = Split("""
board.c
drv_interrupt.c
drv_pin.c
linker_scripts/link.icf
""")

if GetDepend(['BSP_USING_EMAC']):
    src += ['drv_emac.c']

if GetDepend(['BSP_USING_HWTIMER0']):
    src += ['drv_hwtimer.c']

if GetDepend(['BSP_USING_LED']):
    src += ['drv_led.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['drv_sdram.c']

if GetDepend('RT_USING_SERIAL'):
    src += ['drv_uart.c']

if GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('RT_USING_RTC'):
    src += ['drv_rtc.c']
if  GetDepend('BSP_USING_I2C'):
    src += ['drv_soft_i2c.c']

if GetDepend("BSP_USING_WDT"):
    src += ['drv_watchdog.c']

if GetDepend("BSP_USING_SPI"):
    src += ["drv_spi.c"]
if GetDepend("BSP_USING_LCD"):
    src += ["drv_lcd.c"]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
