// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_TABVIEW1_H
#define _UI_COMP_TABVIEW1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT TabView1
#define UI_COMP_TABVIEW1_TABVIEW1 0
#define UI_COMP_TABVIEW1_TABPAGE2 1
#define UI_COMP_TABVIEW1_TABPAGE2_BUTTON1 2
#define UI_COMP_TABVIEW1_TABPAGE2_SWITCH2 3
#define UI_COMP_TABVIEW1_TABPAGE2_TEXTAREA1 4
#define UI_COMP_TABVIEW1_TABPAGE3 5
#define UI_COMP_TABVIEW1_TABPAGE4 6
#define UI_COMP_TABVIEW1_TABPAGE5 7
#define _UI_COMP_TABVIEW1_NUM 8
lv_obj_t * ui_TabView1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
