// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_STATEBAR_H
#define _UI_COMP_STATEBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT stateBar
    enum UI_COMP_STATE_BAR
    {
        STATE_BAR_TIPS,
        STATE_BAR_DATE,
        STATE_BAR_NUM,
    };
    lv_obj_t *ui_stateBar_create(lv_obj_t *comp_parent);
    void stateBar_update_tips(lv_obj_t *statebar, const char *string);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
