// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp_titlebar.h"
#include "ui_comp.h"
#include <stdio.h>
#include "system_var.h"
#include "ui_comp_edit.h"
uint32_t LV_EVENT_SET_TITLE;
uint32_t LV_EVENT_SET_LED_MODE;
uint32_t LV_EVENT_SET_LED_Value;
uint32_t LV_EVENT_SET_LED_Value;

static void update_led(void *parent, int32_t bar_value)
{
    lv_obj_t *led_r = ui_comp_get_child(parent, TITLE_BAR_LED_R);
    lv_obj_t *led_g = ui_comp_get_child(parent, TITLE_BAR_LED_G);
    lv_obj_t *led_y = ui_comp_get_child(parent, TITLE_BAR_LED_Y);
    if (led_g == NULL)
    {
        return;
    }

    if (bar_value % 1 == 0)
    {
        lv_led_toggle(led_y);
    }

    if (bar_value % 5 == 0)
    {
        lv_led_toggle(led_g);
    }

    if (bar_value % 10 == 0)
    {
        lv_led_toggle(led_r);
    }
}
static void lv_event_set_title(lv_event_t *e)
{
    char *title = lv_event_get_param(e);
    lv_obj_t *obj = lv_event_get_target(e);
    lv_obj_t *ui_title = ui_comp_get_child(obj, TITLE_BAR_TITLE);
    if (title)
        lv_label_set_text(ui_title, title);
}
static void del_component_title_event_cb(lv_event_t *e)
{
    lv_anim_del(NULL, update_led);
}
lv_obj_t *ui_titleBar_create(lv_obj_t *comp_parent)
{

    lv_obj_t *obj;
    obj = lv_obj_create(comp_parent);
    lv_obj_set_style_pad_top(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_coord_t col_dsc[] = {LV_GRID_FR(1), 16, 16, 16, LV_GRID_TEMPLATE_LAST};
    static lv_coord_t row_dsc[] = {LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    lv_obj_set_grid_dsc_array(obj, col_dsc, row_dsc);
    lv_obj_center(obj);

    lv_obj_t *ui_title = lv_label_create(obj);
    lv_obj_set_grid_cell(ui_title, LV_GRID_ALIGN_START, 0, 1,
                         LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_set_width(ui_title, 429);
    lv_obj_set_height(ui_title, 30);
    lv_obj_set_align(ui_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_title, "");
    lv_obj_set_style_text_color(ui_title, lv_color_hex(0x00B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_title, &ui_font_heiti24, (lv_part_t)LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *led_y = lv_led_create(obj);
    lv_obj_set_grid_cell(led_y, LV_GRID_ALIGN_START, 1, 1,
                         LV_GRID_ALIGN_CENTER, 0, 1);
    lv_led_set_brightness(led_y, 255);
    lv_obj_set_style_shadow_spread(led_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_led_set_color(led_y, lv_palette_main(LV_PALETTE_YELLOW));
    lv_obj_set_size(led_y, 16, 16);

    lv_obj_t *led_g = lv_led_create(obj);
    lv_obj_set_grid_cell(led_g, LV_GRID_ALIGN_START, 2, 1,
                         LV_GRID_ALIGN_CENTER, 0, 1);
    lv_led_set_brightness(led_g, 255);
    lv_obj_set_style_shadow_spread(led_g, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_led_set_color(led_g, lv_palette_main(LV_PALETTE_GREEN));
    lv_obj_set_size(led_g, 16, 16);

    lv_obj_t *led_r = lv_led_create(obj);
    lv_obj_set_grid_cell(led_r, LV_GRID_ALIGN_START, 3, 1,
                         LV_GRID_ALIGN_CENTER, 0, 1);
    lv_led_set_brightness(led_r, 255);
    lv_obj_set_style_shadow_spread(led_r, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_led_set_color(led_r, lv_palette_main(LV_PALETTE_RED));
    lv_obj_set_size(led_r, 16, 16);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * TITLE_BAR_NUM);
    lv_memset_00(children, sizeof(lv_obj_t *) * TITLE_BAR_NUM);
    children[TITLE_BAR_TITLE] = ui_title;
    children[TITLE_BAR_LED_Y] = led_y;
    children[TITLE_BAR_LED_G] = led_g;
    children[TITLE_BAR_LED_R] = led_r;
    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    /** add user event */
    lv_obj_add_event_cb(obj, del_component_title_event_cb, LV_EVENT_DELETE, NULL);

    if (LV_EVENT_SET_TITLE == 0)
    {
        LV_EVENT_SET_TITLE = lv_event_register_id();
    }
    lv_obj_add_event_cb(obj, lv_event_set_title, LV_EVENT_SET_TITLE, NULL);

    /*!< LED闪烁动画 */
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_exec_cb(&a, update_led);
    lv_anim_set_time(&a, 10000); /*!< 3000ms 动画时间 */
    lv_anim_set_var(&a, obj);
    lv_anim_set_values(&a, 0, 100); /*!< 动画从0到100 */
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&a);
    // lv_timer_t *time_data_update = lv_timer_create(time_update, 500, cui_date);

    return obj;
}

