// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_DASHBOARD_CTL_H
#define _UI_COMP_DASHBOARD_CTL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT stateBar
    enum UI_COMP_DASHBOARD_CTL
    {
        DASHBOARD_CTL_CHN_SEL,

        DASHBOARD_CTL_NUM,
    };
    lv_obj_t *ui_Dashboard_ctl_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
