// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp_page_Dashboard_sensor.h"
#include "ui_comp.h"
#include <stdio.h>
#include "system_var.h"
#include "thread_DTS.h"
#include "sensor_var.h"
static void time_update(lv_timer_t *ptime)
{
    lv_obj_t *obj = (lv_obj_t *)ptime->user_data;
    lv_event_send(obj, LV_EVENT_NOTIFY_UPDATE, (void *)-1);
}
static void lv_event_notify_page(lv_event_t *e)
{
    static lv_timer_t *timer = 0;
    /*!< 通知发生了页面也换，可能不是活动状态，将关闭刷新功能 */
    uint32_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (code == LV_EVENT_NOTIFY_PAGE_ACT)
    {
        lv_event_send(obj, LV_EVENT_NOTIFY_UPDATE, (void *)-1);
        /** 定时刷新的 任务*/
        if (timer == 0)
        {
            timer = lv_timer_create(time_update, 1000, obj);
        }
    }
    if (code == LV_EVENT_NOTIFY_PAGE_CHANGE)
    {
        if (timer)
        {
            lv_timer_del(timer);
            timer = 0;
        }
    }
}
static void lv_event_value_update(lv_event_t *e)
{
    uint32_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);

    if (code == LV_EVENT_NOTIFY_UPDATE)
    {
        uint8_t idx = 0;
        for (size_t i = DASHBOARD_SEN_LABEL_VAL; i < DASHBOARD_SEN_LABEL_VAL_ED; i += 2)
        {
            lv_obj_t *label_obj = ui_comp_get_child(obj, i);
            lv_obj_t *value_obj = ui_comp_get_child(obj, i + 1);
            if (label_obj && value_obj)
            {
                if ((idx < g_sensor_param.sensor_num) &&
                    (g_sensor_param.sen_config[idx].type < SEN_NUM))
                {
                    lv_obj_clear_flag(label_obj, LV_OBJ_FLAG_HIDDEN);
                    lv_obj_clear_flag(value_obj, LV_OBJ_FLAG_HIDDEN);
                    lv_label_set_text(label_obj, rom_sensor_var[g_sensor_param.sen_config[idx].type].fullname);
                    char strbuff[16];
                    if (g_var_work.Sensor[idx].SenSat != 0x0F)
                    {
                         sprintf(strbuff, "--%s", rom_sensor_var[g_sensor_param.sen_config[idx].type].unit);
                        lv_label_set_text(value_obj, strbuff);
                        lv_obj_set_style_text_color(value_obj, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN | LV_STATE_DEFAULT);
                    }
                    else
                    {
                        sprintf(strbuff, "%.2f%s", g_var_work.Sensor[idx].SenData[0], rom_sensor_var[g_sensor_param.sen_config[idx].type].unit);
                        lv_label_set_text(value_obj, strbuff);
                        lv_obj_set_style_text_color(value_obj, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
                    }
                }
                else
                {
                    lv_obj_add_flag(label_obj, LV_OBJ_FLAG_HIDDEN);
                    lv_obj_add_flag(value_obj, LV_OBJ_FLAG_HIDDEN);
                }
                idx++;
            }
        }
    }
}

lv_obj_t *ui_Dashboard_sensor_create(lv_obj_t *comp_parent)
{

    lv_obj_t *obj;
    obj = lv_obj_create(comp_parent);
    lv_obj_add_event_cb(obj, lv_event_notify_page, LV_EVENT_NOTIFY_PAGE_CHANGE, NULL);
    lv_obj_add_event_cb(obj, lv_event_notify_page, LV_EVENT_NOTIFY_PAGE_ACT, NULL);
    lv_obj_add_event_cb(obj, lv_event_value_update, LV_EVENT_NOTIFY_UPDATE, NULL); /*!< 通知刷新后，初始化所有控件 */

    lv_obj_set_style_pad_top(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_coord_t col_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static lv_coord_t row_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    lv_obj_set_grid_dsc_array(obj, col_dsc, row_dsc);
    lv_obj_center(obj);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * DASHBOARD_SEN_NUM);
    lv_memset_00(children, sizeof(lv_obj_t *) * DASHBOARD_SEN_NUM);

    for (size_t i = DASHBOARD_SEN_LABEL_VAL; i < DASHBOARD_SEN_LABEL_VAL_ED; i++)
    {
        lv_obj_t *label_obj = lv_label_create(obj);
        lv_obj_set_grid_cell(label_obj, LV_GRID_ALIGN_START, 0, 1,
                             LV_GRID_ALIGN_CENTER, i / 2, 1);
        lv_obj_align(label_obj, LV_ALIGN_TOP_MID, 0, 20);
        lv_label_set_text(label_obj, "");
        children[i] = label_obj;
        lv_obj_add_flag(label_obj, LV_OBJ_FLAG_HIDDEN);
        i++;
        label_obj = lv_label_create(obj);
        lv_obj_set_grid_cell(label_obj, LV_GRID_ALIGN_START, 1, 1,
                             LV_GRID_ALIGN_CENTER, i / 2, 1);
        lv_obj_align(label_obj, LV_ALIGN_TOP_MID, 0, 20);
        lv_label_set_text(label_obj, "");
        lv_obj_add_flag(label_obj, LV_OBJ_FLAG_HIDDEN);
        children[i] = label_obj;
    }
    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    /** add user event */

    return obj;
}
