// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_TITLE_BAR_H
#define _UI_COMP_TITLE_BAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT stateBar
    enum UI_COMP_TITLE_BAR
    {
        TITLE_BAR_TITLE,
        TITLE_BAR_LED_R,
        TITLE_BAR_LED_G,
        TITLE_BAR_LED_Y,
        TITLE_BAR_NUM,
    };
    extern uint32_t LV_EVENT_SET_TITLE;
    extern uint32_t LV_EVENT_SET_LED_MODE;
    extern uint32_t LV_EVENT_SET_LED_Value;
    extern uint32_t LV_EVENT_SET_LED_Value;

    lv_obj_t *ui_titleBar_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
