// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp_page_Dashboard_ctl.h"
#include "ui_comp.h"
#include <stdio.h>
#include "system_var.h"
#include "thread_DTS.h"
static void lv_event_value_changed(lv_event_t *e)
{
    // char *param = lv_event_get_param(e);
    lv_obj_t *obj = lv_event_get_target(e);
    lv_obj_t *dd = ui_comp_get_child(obj, DASHBOARD_CTL_CHN_SEL);
    if (dd && g_var_work.dts)
    {
        thread_dts_t *pdts = g_var_work.dts;
        dts_data_t *pdata = &pdts->data;
        char buff[128];
        if (pdts == 0 || pdts->offline == 1 || pdata->system.status == 0)
        {
            sprintf(buff, "dts offline");
            lv_dropdown_set_selected(dd, 0);
        }
        else
        {
            uint32_t offset = 0;
            for (size_t i = 0; i < pdata->system.chn_num; i++)
            {
                offset += sprintf(buff + offset, "ch%02d\n", i + 1);
            }
            buff[offset - 1] = '\0';
        }

        lv_dropdown_set_options(dd, buff);
    }
}
static void dd_event_handler(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (obj && code == LV_EVENT_VALUE_CHANGED)
    {
        uint32_t chn_sel = 0;
        chn_sel = lv_dropdown_get_selected(obj);
        if (g_var_work.dts)
        {
            thread_DTS_control(TH_DTH_SET_CHN_RANGE, &chn_sel);
        }
    }
}
static void lv_event_value_changed_spinbox(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (code == LV_EVENT_VALUE_CHANGED)
    {
        char buf[32];
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
        if (g_var_work.dts)
        {
            // g_var_work.dts->sel_chn=;
        }
    }
}
lv_obj_t *ui_Dashboard_ctl_create(lv_obj_t *comp_parent)
{

    lv_obj_t *obj;
    obj = lv_obj_create(comp_parent);
    lv_obj_set_style_pad_top(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_coord_t col_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static lv_coord_t row_dsc[] = {LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    lv_obj_set_grid_dsc_array(obj, col_dsc, row_dsc);
    lv_obj_center(obj);
    lv_obj_t *label_obj_1 = lv_label_create(obj);
    lv_obj_set_grid_cell(label_obj_1, LV_GRID_ALIGN_START, 0, 1,
                         LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_align(label_obj_1, LV_ALIGN_TOP_MID, 0, 20);
    lv_label_set_text(label_obj_1, "select chn");

    lv_obj_t *dd = lv_dropdown_create(obj);
    lv_obj_set_grid_cell(dd, LV_GRID_ALIGN_START, 1, 1,
                         LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_align(dd, LV_ALIGN_TOP_MID, 0, 20);
    lv_obj_add_event_cb(dd, dd_event_handler, LV_EVENT_VALUE_CHANGED, NULL);

    // lv_obj_t *label_obj_2 = lv_label_create(obj);
    // lv_obj_set_grid_cell(label_obj_2, LV_GRID_ALIGN_START, 2, 1,
    //                      LV_GRID_ALIGN_CENTER, 0, 1);
    // lv_obj_align(label_obj_2, LV_ALIGN_TOP_MID, 0, 20);
    // lv_label_set_text(label_obj_2, "reflash time");

    // lv_obj_t *label_span = lv_spinbox_create(obj);
    // lv_obj_set_grid_cell(label_span, LV_GRID_ALIGN_START, 3, 1,
    //                      LV_GRID_ALIGN_CENTER, 0, 1);
    // lv_obj_align(label_span, LV_ALIGN_TOP_MID, 0, 20);
    // lv_spinbox_set_range(label_span, 0, g_var_init.dts_delayms_max);
    // lv_spinbox_set_digit_format(label_span, 5, 0);
    // lv_spinbox_step_prev(label_span);
    // lv_obj_set_width(label_span, 100);
    // lv_obj_center(label_span);
    // lv_obj_add_event_cb(label_span, lv_event_value_changed_spinbox, LV_EVENT_VALUE_CHANGED, NULL);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * DASHBOARD_CTL_NUM);
    children[DASHBOARD_CTL_CHN_SEL] = dd;

    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    /** add user event */
    lv_obj_add_event_cb(obj, lv_event_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    return obj;
}
