// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_TABVIEW_MAIN_H
#define _UI_COMP_TABVIEW_MAIN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT TabView1
    enum UI_COMP_TABLEVIEW_MAIN
    {
        UI_COMP_TABVIEW_MAIN_DASHBOARD,
        UI_COMP_TABVIEW_MAIN_SEN_CONFIG,
        UI_COMP_TABVIEW_MAIN_SETING,
        UI_COMP_TABVIEW_MAIN_ABOUT,
        UI_COMP_TABVIEW_MAIN_NUM
    };
    lv_obj_t *ui_TabView_main_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
