// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_STATEBAR_H
#define _UI_COMP_STATEBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT stateBar
#define UI_COMP_STATEBAR_STATEBAR 0
#define UI_COMP_STATEBAR_TIPS 1
#define UI_COMP_STATEBAR_DATE 2
#define _UI_COMP_STATEBAR_NUM 3
lv_obj_t * ui_stateBar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
