// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT TabView1

lv_obj_t * ui_TabView1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_TabView1;
    cui_TabView1 = lv_tabview_create(comp_parent, LV_DIR_LEFT, 50);
    lv_obj_set_width(cui_TabView1, 480);
    lv_obj_set_height(cui_TabView1, 200);
    lv_obj_set_x(cui_TabView1, 0);
    lv_obj_set_y(cui_TabView1, 40);
    lv_obj_set_flex_flow(cui_TabView1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(cui_TabView1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_TabView1, lv_color_hex(0xDBDBEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_TabView1, &ui_font_heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_TabPage2;
    cui_TabPage2 = lv_tabview_add_tab(cui_TabView1, "系统");
    lv_obj_set_flex_flow(cui_TabPage2, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(cui_TabPage2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    lv_obj_t * cui_Button1;
    cui_Button1 = lv_btn_create(cui_TabPage2);
    lv_obj_set_width(cui_Button1, 100);
    lv_obj_set_height(cui_Button1, 50);
    lv_obj_set_align(cui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Switch2;
    cui_Switch2 = lv_switch_create(cui_TabPage2);
    lv_obj_set_width(cui_Switch2, 50);
    lv_obj_set_height(cui_Switch2, 25);
    lv_obj_set_x(cui_Switch2, -46);
    lv_obj_set_y(cui_Switch2, 69);
    lv_obj_set_align(cui_Switch2, LV_ALIGN_CENTER);

    lv_obj_t * cui_TextArea1;
    cui_TextArea1 = lv_textarea_create(cui_TabPage2);
    lv_obj_set_width(cui_TextArea1, lv_pct(100));
    lv_obj_set_height(cui_TextArea1, lv_pct(60));
    lv_obj_set_x(cui_TextArea1, -205);
    lv_obj_set_y(cui_TextArea1, -23);
    lv_textarea_set_placeholder_text(cui_TextArea1, "Placeholder...");

    lv_obj_t * cui_TabPage3;
    cui_TabPage3 = lv_tabview_add_tab(cui_TabView1, "模块");

    lv_obj_t * cui_TabPage4;
    cui_TabPage4 = lv_tabview_add_tab(cui_TabView1, "高级");

    lv_obj_t * cui_TabPage5;
    cui_TabPage5 = lv_tabview_add_tab(cui_TabView1, "关于");

//    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TABVIEW1_NUM);
//    children[UI_COMP_TABVIEW1_TABVIEW1] = cui_TabView1;
//    children[UI_COMP_TABVIEW1_TABPAGE2] = cui_TabPage2;
//    children[UI_COMP_TABVIEW1_TABPAGE2_BUTTON1] = cui_Button1;
//    children[UI_COMP_TABVIEW1_TABPAGE2_SWITCH2] = cui_Switch2;
//    children[UI_COMP_TABVIEW1_TABPAGE2_TEXTAREA1] = cui_TextArea1;
//    children[UI_COMP_TABVIEW1_TABPAGE3] = cui_TabPage3;
//    children[UI_COMP_TABVIEW1_TABPAGE4] = cui_TabPage4;
//    children[UI_COMP_TABVIEW1_TABPAGE5] = cui_TabPage5;
//    lv_obj_add_event_cb(cui_TabView1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
//    lv_obj_add_event_cb(cui_TabView1, del_component_child_event_cb, LV_EVENT_DELETE, children);
//    ui_comp_TabView1_create_hook(cui_TabView1);
    return cui_TabView1;
}

