// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp_tabview_main.h"
// COMPONENT TabView1
#include "ui_tabview_page_Dashboard.h"
#include "ui_tabview_page_sen_config.h"

static void btns_value_changed_event_cb(lv_event_t *e)
{ // char *param = lv_event_get_param(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (NULL == obj)
    {
        return;
    }
    // uint32_t id = lv_btnmatrix_get_selected_btn(obj);
    // lv_event_send(lv_tabview_get_tab_act(lv_obj_get_parent(obj)), LV_EVENT_VALUE_CHANGED, NULL);
}

lv_obj_t *ui_TabView_main_create(lv_obj_t *comp_parent)
{

    lv_obj_t *obj;
    obj = lv_tabview_create(comp_parent, LV_DIR_LEFT, 100);
    lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(obj, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(lv_tabview_get_content(obj), LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xDBDBEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(obj, &lv_font_simhei_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *dashboard = ui_tabview_page_dashboard_create(obj);
    lv_obj_t *sen_config = ui_tabview_page_sen_config_create(obj);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * UI_COMP_TABVIEW_MAIN_NUM);
    children[UI_COMP_TABVIEW_MAIN_DASHBOARD] = dashboard;
    children[UI_COMP_TABVIEW_MAIN_SETING] = obj;
    children[UI_COMP_TABVIEW_MAIN_SEN_CONFIG] = sen_config;
    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    lv_obj_add_event_cb(lv_tabview_get_tab_btns(obj), btns_value_changed_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    _lv_event_child_notify(lv_tabview_get_content(obj), LV_EVENT_VALUE_CHANGED, (void *)-1);
    return obj;
}
