// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT stateBar

lv_obj_t * ui_stateBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_stateBar;
    cui_stateBar = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_stateBar, 30);
    lv_obj_set_width(cui_stateBar, lv_pct(100));
    lv_obj_set_align(cui_stateBar, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(cui_stateBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_stateBar, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_stateBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_stateBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_tips;
    cui_tips = lv_label_create(cui_stateBar);
    lv_obj_set_width(cui_tips, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(cui_tips, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_tips, -217);
    lv_obj_set_y(cui_tips, 2);
    lv_obj_set_align(cui_tips, LV_ALIGN_CENTER);
    lv_label_set_text(cui_tips, "tips");

    lv_obj_t * cui_date;
    cui_date = lv_label_create(cui_stateBar);
    lv_obj_set_width(cui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_date, 166);
    lv_obj_set_y(cui_date, 2);
    lv_obj_set_align(cui_date, LV_ALIGN_CENTER);
    lv_label_set_text(cui_date, "2023-07-27 12:00:00");
//
//    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_STATEBAR_NUM);
//    children[UI_COMP_STATEBAR_STATEBAR] = cui_stateBar;
//    children[UI_COMP_STATEBAR_TIPS] = cui_tips;
//    children[UI_COMP_STATEBAR_DATE] = cui_date;
//    lv_obj_add_event_cb(cui_stateBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
//    lv_obj_add_event_cb(cui_stateBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
//    ui_comp_stateBar_create_hook(cui_stateBar);
    return cui_stateBar;
}

