// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp_edit.h"
#include "ui_comp.h"
#include <stdio.h>

static void ta_event_cb(lv_event_t *e)
{
    lv_indev_t *indev = lv_indev_get_act();
    if (indev == NULL)
        return;
    lv_indev_type_t indev_type = lv_indev_get_type(indev);

    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *ta = lv_event_get_target(e);
    lv_obj_t *kb = lv_event_get_user_data(e);

    if (code == LV_EVENT_CLICKED &&
        (LV_INDEV_TYPE_POINTER == indev_type || indev_type == LV_INDEV_TYPE_ENCODER))
    {
    }

    if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL)
    {
        lv_obj_add_flag(lv_obj_get_parent(ta), LV_OBJ_FLAG_HIDDEN);
    }
}
void ui_edit_pop_with_default(lv_obj_t *obj, const char *string)
{
    if (0 == obj)
        return;

    lv_obj_t *kb = ui_comp_get_child(obj, EDIT_KEYBOARD);
    lv_obj_t *text = ui_comp_get_child(obj, EDIT_TEXTAREA);
    if (0 == text || 0 == kb)
        return;
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_clear_flag(text, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(lv_textarea_get_label(text), string);
    lv_textarea_set_cursor_pos(text, LV_TEXTAREA_CURSOR_LAST);
    lv_obj_add_state(text, LV_STATE_FOCUSED); /*To be sure the cursor is visible*/
}

bool ui_edit_add_event(lv_obj_t *obj, lv_event_cb_t event_cb, lv_event_code_t filter, void *user_data)
{
    if (0 == obj)
        return false;

    lv_obj_t *text = ui_comp_get_child(obj, EDIT_TEXTAREA);
    if (0 == text)
        return false;
    lv_obj_add_event_cb(text, event_cb, filter, user_data);

    return true;
}
const char *ui_edit_get_text(lv_obj_t *obj)
{
    if (0 == obj)
        return NULL;

    lv_obj_t *text = ui_comp_get_child(obj, EDIT_TEXTAREA);
    if (0 == text)
        return NULL;
    return lv_textarea_get_text(text);
}
lv_obj_t *ui_edit_create(lv_obj_t *comp_parent)
{

    lv_obj_t *obj = NULL;

    obj = lv_obj_create(comp_parent);
    lv_obj_add_flag(obj, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_pad_top(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_coord_t col_dsc[] = {LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static lv_coord_t row_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(4), LV_GRID_TEMPLATE_LAST};
    lv_obj_set_grid_dsc_array(obj, col_dsc, row_dsc);
    lv_obj_center(obj);

    lv_obj_t *ui_text = lv_textarea_create(obj);
    lv_obj_set_grid_cell(ui_text, LV_GRID_ALIGN_CENTER, 0, 1,
                         LV_GRID_ALIGN_CENTER, 0, 1);
    lv_obj_add_event_cb(ui_text, ta_event_cb, LV_EVENT_READY, NULL);
    lv_obj_add_event_cb(ui_text, ta_event_cb, LV_EVENT_CANCEL, NULL);
    lv_textarea_set_one_line(ui_text, true);

    lv_obj_t *kb = lv_keyboard_create(obj);
    lv_obj_set_grid_cell(kb, LV_GRID_ALIGN_CENTER, 0, 1,
                         LV_GRID_ALIGN_CENTER, 1, 1);
    lv_keyboard_set_mode(kb, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_style_text_font(kb, LV_FONT_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_keyboard_set_textarea(kb, obj);
    lv_obj_set_size(kb, 400, 300);
    lv_obj_center(obj);
    lv_obj_align(kb, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_keyboard_set_textarea(kb, ui_text);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * EDIT_NUM);
    lv_memset_00(children, sizeof(lv_obj_t *) * EDIT_NUM);
    children[EDIT_TEXTAREA] = ui_text;
    children[EDIT_KEYBOARD] = kb;
    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    /** add user event */

    return obj;
}
