// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_DASHBOARD_SENSOR_H
#define _UI_COMP_DASHBOARD_SENSOR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT stateBar
    enum UI_COMP_DASHBOARD_SEN
    {
        DASHBOARD_SEN_LABEL_VAL, /*!< 0 label 1 value */
        DASHBOARD_SEN_LABEL_VAL_ED = DASHBOARD_SEN_LABEL_VAL + 2 * 5,

        DASHBOARD_SEN_NUM,
    };
    lv_obj_t *ui_Dashboard_sensor_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
