// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_P00startup_screen_init(void)
{
    ui_P00startup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_P00startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_P00startup, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_P00startup, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_set_style_bg_color(ui_P00startup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P00startup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_P00startup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_P00startup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_P00startup, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_P00startup, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_P00startup);
    lv_img_set_src(ui_logo, &ui_img_logo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo, 30);
    lv_obj_set_y(ui_logo, 69);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_startBar = ui_startBar_create(ui_P00startup);
    lv_obj_set_x(ui_startBar, -18);
    lv_obj_set_y(ui_startBar, 94);

    lv_obj_add_event_cb(ui_P00startup, ui_event_P00startup, LV_EVENT_ALL, NULL);

}
