// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp_head.h"
#include "ui_comp_statebar.h"
#include "lv_group_manage.h"
#include "ui_tableview_P02_baseSetting.h"
static lv_group_manage_t s_group_manage;
lv_obj_t *ui_P02factory = NULL;
void ui_event_P02factory(lv_event_t *e);
void ui_P02factory_screen_init(void)
{
    group_init_begin(&s_group_manage);
    ui_P02factory = lv_obj_create(NULL);
    // lv_obj_clear_flag(ui_P02factory, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_flex_flow(ui_P02factory, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_P02factory, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_BETWEEN);

    lv_obj_t *ui_TabView1 = lv_tabview_create(ui_P02factory, LV_DIR_LEFT, 50);
    lv_obj_set_size(ui_TabView1, lv_pct(100), lv_pct(100));
    lv_obj_set_pos(ui_TabView1, 0, 0);

    lv_obj_set_flex_flow(ui_TabView1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_TabView1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xDBDBEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabView1, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *ui_TabPage;
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "基本配置");
    lv_tablepage_baseSetting_create(ui_TabPage);
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "测量配置");
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "模块配置");
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "测量标定");
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "系统状态");
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "异常信息");
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "0点屏蔽");
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "气体配置1");
    ui_TabPage = lv_tabview_add_tab(ui_TabView1, "气体配置2");

    lv_obj_t *lv_mbtn = lv_tabview_get_tab_btns(ui_TabView1);
    lv_btnmatrix_set_one_checked(lv_mbtn, true);
    lv_obj_add_flag(lv_mbtn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_size(lv_mbtn, lv_pct(20), lv_pct(100));



        lv_obj_add_event_cb(ui_P02factory, ui_event_P02factory, LV_EVENT_ALL, NULL);
    group_init_end(&s_group_manage);
}
void ui_event_P02factory(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        group_init_loaded(&s_group_manage);
    }
    if (event_code == LV_EVENT_SCREEN_UNLOADED)
    {
        group_init_unloaded(&s_group_manage);
    }
}
