// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#define DBG_TAG "LVGL.ui"
#define DBG_LVL DBG_INFO
#include <rtdbg.h>

#include <drivers/rtc.h>
#include "ui_comp_head.h"
#include "ui_comp_statebar.h"
#include "ui_tableview_module_state.h"
#include "ui_tableview_about.h"
#include "lv_group_manage.h"
// SCREEN: ui_P01main
void ui_P01main_screen_init(void);
lv_obj_t *ui_P01main;
lv_obj_t *ui_head;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_stateBar;

static lv_group_manage_t s_group_manage;
// lv_obj_t* ui____initial_actions0;

LV_FONT_DECLARE(ui_font_heiti16);
LV_FONT_DECLARE(ui_font_heiti24);

void ui_event_P01main(lv_event_t *e);
void time_state_cb(struct _lv_timer_t *date);
void lv_tablepage_measure_create(lv_obj_t *parent);
void lv_tablepage_system_create(lv_obj_t *parent);
void lv_example_table_2(lv_obj_t *parent);
lv_obj_t *ui_super_create(lv_obj_t *parent);
void ui_event_tableview(lv_event_t *e);
void ui_P01main_screen_init(void)
{
	group_init_begin(&s_group_manage);
	ui_P01main = lv_obj_create(NULL);
	lv_obj_clear_flag(ui_P01main, LV_OBJ_FLAG_SCROLLABLE); /// Flags
	lv_obj_set_grid_align(ui_P01main, 1, 6);
	lv_obj_set_flex_flow(ui_P01main, LV_FLEX_FLOW_ROW_WRAP);
	lv_obj_set_flex_align(ui_P01main, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_BETWEEN);

	ui_head = ui_head_create(ui_P01main);
	lv_obj_set_size(ui_head, lv_pct(100), 40);
	lv_obj_clear_flag(ui_head, LV_OBJ_FLAG_SCROLLABLE); /// Flags
	lv_obj_set_style_radius(ui_head, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_TabView1 = lv_tabview_create(ui_P01main, LV_DIR_LEFT, 50);
	lv_obj_set_width(ui_TabView1, 480);
	lv_obj_set_height(ui_TabView1, 200);
	lv_obj_set_x(ui_TabView1, 0);
	lv_obj_set_y(ui_TabView1, 40);
	lv_obj_set_flex_flow(ui_TabView1, LV_FLEX_FLOW_ROW_WRAP);
	lv_obj_set_flex_align(ui_TabView1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
	lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
	lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xDBDBEA), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_TabView1, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_t *ui_TabPage1;
	lv_obj_t *ui_TabPage2;
	lv_obj_t *ui_TabPage3;
	lv_obj_t *ui_TabPage4;
	lv_obj_t *ui_TabPage5;
	ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "测量");

	ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "系统");

	ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "模块");

	ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "高级");

	ui_TabPage5 = lv_tabview_add_tab(ui_TabView1, "关于");

	lv_obj_add_event_cb(ui_TabView1, ui_event_tableview, LV_EVENT_VALUE_CHANGED, NULL);

	ui_stateBar = ui_stateBar_create(ui_P01main);
	lv_obj_set_height(ui_stateBar, 30);
	lv_obj_set_width(ui_stateBar, lv_pct(100));

	lv_obj_add_event_cb(ui_P01main, ui_event_P01main, LV_EVENT_ALL, NULL);
	lv_tablepage_measure_create(ui_TabPage1);
	lv_tablepage_system_create(ui_TabPage2);
	ui_module_state_create(ui_TabPage3);
	ui_super_create(ui_TabPage4);
	lv_tablepage_about_create(ui_TabPage5);
	// lv_example_table_2(ui_TabPage3);
	group_init_end(&s_group_manage);
}

void ui_event_P01main(lv_event_t *e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t *target = lv_event_get_target(e);
	if (event_code == LV_EVENT_SCREEN_LOADED)
	{
		group_init_loaded(&s_group_manage);
		lv_obj_clear_flag(target, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_flag(target, LV_OBJ_FLAG_CLICK_FOCUSABLE);
		lv_obj_clear_flag(target, LV_OBJ_FLAG_CHECKABLE);
	}
	if (event_code == LV_EVENT_SCREEN_UNLOADED)
	{
		group_init_unloaded(&s_group_manage);
	}
}
void ui_event_tableview(lv_event_t *e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t *target = lv_event_get_target(e);
	lv_obj_t *current_target = lv_event_get_current_target(e);
	lv_obj_t *userdate = lv_event_get_user_data(e);
}
