// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_P00startup
void ui_P00startup_screen_init(void);
void ui_event_P00startup(lv_event_t * e);
extern lv_obj_t * ui_P00startup;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_startBar;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo_png);    // assets\logo.png

LV_FONT_DECLARE(ui_font_simhei12);
LV_FONT_DECLARE(ui_font_simhei16);
LV_FONT_DECLARE(ui_font_simhei24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
