// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#define DBG_TAG    "LVGL.ui"
#define DBG_LVL    DBG_INFO
#include <rtdbg.h>
#include "stdio.h"

void P00_systemStart(lv_event_t * e)
{
	// Your code here
}
void time_process_cb(struct _lv_timer_t*); 
lv_timer_t* time_handle = NULL;
void P00_lvglStart(lv_event_t * e)
{
	// Your code here
	LOG_I("P00_lvglStart");
	time_handle =lv_timer_create(time_process_cb, 50, NULL);
}
void ui_P01main_screen_init(void);
extern lv_obj_t* ui_P01main;
void time_process_cb(struct _lv_timer_t* date)
{
	int32_t  currValue=lv_bar_get_value(ui_startBar);
	if (currValue < 100)
	{
		currValue++;
		lv_bar_set_value(ui_startBar, currValue, LV_ANIM_ON);
	}
	else
	{
		lv_timer_del(time_handle);
		time_handle = NULL;
		_ui_screen_change(&ui_P01main, LV_SCR_LOAD_ANIM_FADE_ON,500, 100,ui_P01main_screen_init);
	}
}