from building import *

cwd = GetCurrentDir()
path = [cwd+'/inc']

# add the general drivers.
src = Split("""
port/adxl345_port.c
""")

src  += Glob('src/*.c')

if  GetDepend('BSP_USING_ADXL345_SHELL'):
  src += ['sample/ADXL345_shell.c']

group = DefineGroup('ADXL345', src, depend = ['BSP_USING_ADXL345'], CPPPATH = path)

Return('group')
