// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_HEAD_H
#define _UI_COMP_HEAD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT HEAD
    enum UI_COMP_HEAD
    {
        UI_COMP_HEAD_PANEL = 0,
        UI_COMP_HEAD_PRODUCTNAME,
        UI_COMP_HEAD_LED_R,
        UI_COMP_HEAD_LED_Y,
        UI_COMP_HEAD_LED_B,
        _UI_COMP_HEAD_NUM
    };
    lv_obj_t *ui_head_create(lv_obj_t *comp_parent);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
