// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT startBar

lv_obj_t * ui_startBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_startBar;
    cui_startBar = lv_bar_create(comp_parent);
    lv_obj_set_width(cui_startBar, 312);
    lv_obj_set_height(cui_startBar, 10);
    lv_obj_set_x(cui_startBar, -18);
    lv_obj_set_y(cui_startBar, 94);
    lv_obj_set_align(cui_startBar, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_STARTBAR_NUM);
    children[UI_COMP_STARTBAR_STARTBAR] = cui_startBar;
    lv_obj_add_event_cb(cui_startBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_startBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_startBar_create_hook(cui_startBar);
    return cui_startBar;
}

