// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project
#include "../ui.h"
#include "ui_comp_statebar.h"
#include "ui_comp_head.h"
#include <drivers/rtc.h>
#include "ui_comp_hook.h"

static lv_timer_t * time_handle = NULL;
static lv_timer_t * time_led_handle = NULL;
static void time_state_cb(struct _lv_timer_t * date);
static void time_led_cb(struct _lv_timer_t * date);
void ui_comp_stateBar_create_hook(lv_obj_t * comp)
{
    time_handle = lv_timer_create(time_state_cb, 500, comp);
}

void ui_comp_module_state_create_hook(lv_obj_t * comp)
{
    //lv_obj_t *p_table = ui_comp_get_child(comp, UI_COMP_MODULE_STATE_TABLE);

}
void ui_comp_startBar_create_hook(lv_obj_t * comp)
{
}
void ui_comp_super_create_hook(lv_obj_t * comp)
{

}
void ui_comp_head_create_hook(lv_obj_t * comp)
{
    time_led_handle = lv_timer_create(time_led_cb, 500, comp);
}

void time_state_cb(struct _lv_timer_t * date)
{
    time_t now;
    lv_obj_t * p_panel = (lv_obj_t *)date->user_data;
    lv_obj_t * p_date = ui_comp_get_child(p_panel, UI_COMP_STATEBAR_DATE);

    char strbuff[32];

    now = time(NULL);
    /* output current time */
    struct tm * tm_ptr;
    tm_ptr = localtime(&now);
    char * format = "%Y-%m-%d %H:%M:%S";
    strftime(strbuff, sizeof(strbuff), format, tm_ptr);
    lv_label_set_text(p_date, strbuff);
}

void time_led_cb(struct _lv_timer_t * date)
{
    lv_obj_t * p_panel = (lv_obj_t *)date->user_data;
    lv_obj_t * p_led_r = ui_comp_get_child(p_panel, UI_COMP_HEAD_LED_R);
    lv_obj_t * p_led_y = ui_comp_get_child(p_panel, UI_COMP_HEAD_LED_Y);
    lv_obj_t * p_led_b = ui_comp_get_child(p_panel, UI_COMP_HEAD_LED_B);
    static uint8_t value = 0;
    value & 0x04 ? lv_led_on(p_led_r) : lv_led_off(p_led_r);
    value & 0x02 ? lv_led_on(p_led_y) : lv_led_off(p_led_y);
    value & 0x01 ? lv_led_on(p_led_b) : lv_led_off(p_led_b);
    value++;
}
