// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_STARTBAR_H
#define _UI_COMP_STARTBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT startBar
#define UI_COMP_STARTBAR_STARTBAR 0
#define _UI_COMP_STARTBAR_NUM 1
lv_obj_t * ui_startBar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
