// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp_head.h"
// COMPONENT stateBar
void ui_comp_head_create_hook(lv_obj_t* comp);
lv_obj_t *ui_head_create(lv_obj_t *comp_parent)
{

    lv_obj_t * cui_head;
    cui_head = lv_obj_create(comp_parent);

    //lv_obj_set_flex_flow(cui_head, LV_FLEX_FLOW_ROW_WRAP);
    //lv_obj_set_flex_align(cui_head, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(cui_head, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(cui_head, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_productName;
    cui_productName = lv_label_create(cui_head);
    lv_obj_set_width(cui_productName, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_productName, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_productName, LV_ALIGN_LEFT_MID);
    lv_obj_set_pos(cui_productName,0,0);
    lv_label_set_text(cui_productName, "矿用本安型激光火情监控主机");
    lv_obj_set_style_text_color(cui_productName, lv_color_hex(0x00B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_productName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_productName, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_led_r;
    cui_led_r = lv_led_create(cui_head);
    lv_led_set_color(cui_led_r, lv_palette_main(LV_PALETTE_RED));
    lv_obj_set_align(cui_led_r, LV_ALIGN_RIGHT_MID);
    lv_obj_set_size(cui_led_r, 20, 20);
    lv_obj_set_pos(cui_led_r, -50, 0);
    lv_obj_set_style_shadow_spread(cui_led_r, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t * cui_led_y;
    cui_led_y = lv_led_create(cui_head);
    lv_led_set_color(cui_led_y, lv_palette_main(LV_PALETTE_YELLOW));
    lv_obj_set_align(cui_led_y, LV_ALIGN_RIGHT_MID);
    lv_obj_set_size(cui_led_y, 20, 20);
    lv_obj_set_pos(cui_led_y, -25, 0);
    lv_obj_set_style_shadow_spread(cui_led_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t * cui_led_b;
    cui_led_b = lv_led_create(cui_head);
    lv_led_set_color(cui_led_b, lv_palette_main(LV_PALETTE_BLUE));
    lv_obj_set_align(cui_led_b, LV_ALIGN_RIGHT_MID);
    lv_obj_set_size(cui_led_b, 20, 20);
    lv_obj_set_pos(cui_led_b, 0, 0);
    lv_obj_set_style_shadow_spread(cui_led_b, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEAD_NUM);
    children[UI_COMP_HEAD_PANEL] = cui_head;
    children[UI_COMP_HEAD_PRODUCTNAME] = cui_productName;
    children[UI_COMP_HEAD_LED_R] = cui_led_r;
    children[UI_COMP_HEAD_LED_Y] = cui_led_y;
    children[UI_COMP_HEAD_LED_B] = cui_led_b;
    lv_obj_add_event_cb(cui_head, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_head, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_head_create_hook(cui_head);
    return cui_head;
}

