// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_tableview_super.h"
#include "ui_comp.h"
#include "varDef.h"
#define DBG_TAG "LVGL.ms"
#define DBG_LVL DBG_INFO
#include <rtdbg.h>
// COMPONENT stateBar

void ui_comp_super_create_hook(lv_obj_t *comp);
void win_passwd_event_cb(lv_event_t *e);
void win_passwd_leave_event_cb(lv_event_t *e);
void win_close_event_cb(lv_event_t *e);
lv_obj_t *ui_super_create(lv_obj_t *comp_parent)
{
	lv_obj_set_align(comp_parent, LV_ALIGN_BOTTOM_LEFT);
	// lv_obj_set_flex_flow(cui_stateBar, LV_FLEX_FLOW_ROW);
	// lv_obj_set_flex_align(cui_stateBar, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
	lv_obj_clear_flag(comp_parent, LV_OBJ_FLAG_SCROLLABLE); /// Flags
	lv_obj_set_style_radius(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	lv_obj_t* pBt= lv_btn_create(comp_parent);
	lv_obj_set_align(pBt, LV_ALIGN_CENTER);
	lv_obj_set_pos(pBt, 0, 0);

	const char *strTips = "请按[确认]键输入用户密码";
	lv_obj_t *p_lable = lv_label_create(pBt);
	lv_obj_set_align(p_lable, LV_ALIGN_CENTER);
	lv_obj_set_pos(p_lable, 0, 0);
	lv_label_set_text(p_lable, strTips);
	lv_obj_set_style_text_font(p_lable, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);
	// lv_obj_add_flag(p_lable,LV_OBJ_FLAG_HIDDEN);//隐藏控件

	// lv_spinbox_set_step(pSpinBox, (uint32_t)round(pow(10, 1 - 1)));

	lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SUPER_NUM);
	children[UI_COMP_SUPER_LABEL_TIPS] = p_lable;

	lv_obj_add_event_cb(comp_parent, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
	lv_obj_add_event_cb(comp_parent, del_component_child_event_cb, LV_EVENT_DELETE, children);
	lv_obj_add_event_cb(pBt, win_passwd_event_cb, LV_EVENT_LONG_PRESSED, NULL);
	// lv_obj_add_event_cb(comp_parent, win_passwd_leave_event_cb, LV_EVENT_DEFOCUSED, p_win);

	ui_comp_super_create_hook(comp_parent);

	return comp_parent;
}

#include "ui_comp_passwd.h"
extern lv_obj_t *ui_P02factory;
void ui_P02factory_screen_init(void);
void win_passwd_cb(lv_event_t *e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t *pObj = lv_event_get_current_target(e);
	lv_obj_t *pWin = (lv_obj_t *)lv_event_get_user_data(e);
	if (LV_EVENT_KEY == event_code)
	{
		lv_indev_type_t indev_type = lv_indev_get_type(lv_indev_get_act());

		uint32_t c = *((uint32_t *)lv_event_get_param(e)); /*uint32_t because can be UTF-8*/

		if (indev_type == LV_INDEV_TYPE_KEYPAD)
		{
			if (c == LV_KEY_ENTER)
			{

				lv_obj_t *pValue = ui_comp_get_child(pWin, UI_COMP_PASSWD_ED_PASSSWD);
				uint32_t passwd = lv_spinbox_get_value(pValue);
				if (passwd == 0000)
				{
					LOG_I("Password verification successful ");
					ui_comp_passwd_hidden(pWin);
					_ui_screen_change(&ui_P02factory, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, ui_P02factory_screen_init);
					
				}
				else
				{
					ui_comp_passwd_hidden(pWin);
					LOG_E("passwd error:%04d ", passwd);
				}

			}
			if (c == LV_KEY_ESC)
			{ // 用户取消了
			}
		}
	}
	//if (pObj == ui_comp_get_child(pWin, UI_COMP_PASSWD_BT_CLOSE))
	//{
	//	LOG_I("close win ");
	//}
}
void win_passwd_event_cb(lv_event_t *e)
{
	lv_obj_t *pObj = lv_event_get_current_target(e);
	lv_obj_t *pWin = ui_comp_passwd_popup(lv_layer_top(), win_passwd_cb);
}
void win_passwd_leave_event_cb(lv_event_t *e)
{
	LOG_I("win_passwd_leave_event_cb");
	lv_obj_t *pObj = lv_event_get_current_target(e);
	lv_obj_t *pWin = (lv_obj_t *)lv_event_get_user_data(e);
}
void win_close_event_cb(lv_event_t *e)
{
	lv_obj_t *pObj = lv_event_get_current_target(e);
	lv_obj_t *pWin = (lv_obj_t *)lv_event_get_user_data(e);

}
