// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_MODULE_STATE_H
#define _UI_COMP_MODULE_STATE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT module state
    enum UI_COMP_SUPER
    {
        UI_COMP_SUPER = 0,
        UI_COMP_SUPER_PASSWORD_TIPS,
        _UI_COMP_MODULE_STATE_NUM
    };

    lv_obj_t *ui_super_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
