// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_P02_BASESETTING_H
#define _UI_COMP_P02_BASESETTING_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT module state
    enum UI_COMP_BASESETTING
    {
        UI_COMP_BASESETTING_DEVID = 0,
        UI_COMP_BASESETTING_SAVE_FACTORY_SETTINGS,
        UI_COMP_BASESETTING_RESTORE_FACTORY_SETTINGS,

        _UI_COMP_BASESETTING_NUM
    };

    lv_obj_t *lv_tablepage_baseSetting_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
