// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_ABOUT_H
#define _UI_COMP_ABOUT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT module state
    enum UI_COMP_ABOUT
    {
        UI_COMP_ABOUT_LABEL_TIPS = 0,
        UI_COMP_ABOUTPANEL_PASSWORD,
        _UI_COMP_ABOUT_NUM
    };

    lv_obj_t * lv_tablepage_about_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
