// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_tableview_module_state.h"
#include "ui_comp.h"
#include "varDef.h"
// COMPONENT stateBar
static lv_timer_t* time_handle = NULL;
static void time_reflash_cb(struct _lv_timer_t*);
void draw_part_event_cb(lv_event_t* e);
void ui_comp_module_state_create_hook(lv_obj_t* comp);
lv_obj_t* ui_module_state_create(lv_obj_t* comp_parent)
{
	lv_obj_set_align(comp_parent, LV_ALIGN_BOTTOM_LEFT);
	// lv_obj_set_flex_flow(cui_stateBar, LV_FLEX_FLOW_ROW);
	// lv_obj_set_flex_align(cui_stateBar, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
	lv_obj_clear_flag(comp_parent, LV_OBJ_FLAG_SCROLLABLE); /// Flags
	lv_obj_set_style_radius(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(comp_parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	lv_obj_t* cui_table;
	cui_table = lv_table_create(comp_parent);
	lv_obj_set_style_text_font(cui_table, &ui_font_simhei12, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_pos(cui_table, 0, 0);
	lv_obj_set_size(cui_table, lv_pct(100), lv_pct(60));
	lv_obj_set_align(cui_table, LV_ALIGN_TOP_LEFT);
	lv_obj_set_style_pad_left(cui_table, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(cui_table, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(cui_table, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(cui_table, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);


	lv_table_set_col_cnt(cui_table, 4);
	// lv_table_set_col_width(ui_table, 0, 80);
	lv_table_set_col_width(cui_table, 1, 60);
	// lv_table_set_col_width(ui_table, 2, 80);
	lv_table_set_col_width(cui_table, 3, 60);
	lv_obj_add_event_cb(cui_table, draw_part_event_cb, LV_EVENT_DRAW_PART_BEGIN, NULL);

	lv_obj_t** children = lv_mem_alloc(sizeof(lv_obj_t*) * _UI_COMP_MODULE_STATE_NUM);
	children[UI_COMP_MODULE_STATE_PANEL] = comp_parent;
	children[UI_COMP_MODULE_STATE_TABLE] = cui_table;
	lv_obj_add_event_cb(comp_parent, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
	lv_obj_add_event_cb(comp_parent, del_component_child_event_cb, LV_EVENT_DELETE, children);
	ui_comp_module_state_create_hook(comp_parent);

	time_handle = lv_timer_create(time_reflash_cb, 1000, cui_table);

	return comp_parent;
}

void time_reflash_cb(struct _lv_timer_t* data)
{

	lv_obj_t* ui_table = (lv_obj_t*)data->user_data;
	uint8_t en_count = 2;
	lv_table_set_cell_value(ui_table, 0, 0, "气体类型");
	lv_table_set_cell_value(ui_table, 0, 1, "状态");
	lv_table_set_cell_value(ui_table, 0, 2, "气体类型");
	lv_table_set_cell_value(ui_table, 0, 3, "状态");

	for (size_t i = 0; i < GAS_TYPE_NUM; i++)
	{
		if (g_varParam.m_sensor_config[i].en)
		{
			lv_table_set_cell_value_fmt(ui_table, en_count / 2, (en_count % 2) * 2, "%s模块", g_varInit.m_sensor_info[i].name);
			lv_table_set_cell_value_fmt(ui_table, en_count / 2, (en_count % 2) * 2 + 1, "%s", en_count%2?"通信断线":"通信正常");

			en_count++;
		}
	}
}
