// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_SCREEN_CALIBRATION_H
#define _UI_SCREEN_CALIBRATION_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT P00_STARTUP
    enum UI_SCREEN_CALIBRATION
    {
        SCREEN_CALIBRATION_TIPS,
        SCREEN_CALIBRATION_LT,
        SCREEN_CALIBRATION_RT,
        SCREEN_CALIBRATION_LB,
        SCREEN_CALIBRATION_RB,
        SCREEN_CALIBRATION_NUM,
    };
    lv_obj_t *ui_calibration_create(lv_obj_t *parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
