// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_calibration.h"
#include "ui_comp.h"
#define LOG_TAG "lv.calib"
#define LOG_LVL LOG_LVL_DBG
#include "rtdbg.h"
void ui_calibration_all_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (LV_EVENT_SHORT_CLICKED == code)
    {
    }
    else if (LV_EVENT_LONG_PRESSED == code)
    {
        lv_indev_t *p_indev = lv_event_get_param(e);
        lv_point_t point;
        lv_indev_get_point(p_indev, &point);
        LOG_D("point(%d,%d)", point.x, point.y);
    }
}
lv_obj_t *ui_calibration_create(lv_obj_t *parent)
{
    lv_obj_t *obj;

    obj = lv_obj_create(parent);
    static lv_coord_t col_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static lv_coord_t row_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    lv_obj_set_grid_dsc_array(obj, col_dsc, row_dsc);
    lv_obj_center(obj);

    lv_obj_t *lable_obj = lv_label_create(obj);
    lv_obj_set_grid_cell(lable_obj, LV_GRID_ALIGN_CENTER, 1, 1,
                         LV_GRID_ALIGN_CENTER, 1, 1);
    lv_label_set_text(lable_obj, "To start calibration, please press and hold each point in sequence");

    lv_obj_t *bt_lt = lv_btn_create(obj);
    lv_obj_set_grid_cell(bt_lt, LV_GRID_ALIGN_START, 0, 1,
                         LV_GRID_ALIGN_START, 0, 1);
    lv_obj_set_style_bg_color(bt_lt, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(bt_lt, LV_OBJ_FLAG_CLICKABLE);

    lv_obj_t *bt_lb = lv_btn_create(obj);
    lv_obj_set_grid_cell(bt_lb, LV_GRID_ALIGN_START, 0, 1,
                         LV_GRID_ALIGN_END, 2, 1);
    lv_obj_clear_flag(bt_lb, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(bt_lb, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *bt_rt = lv_btn_create(obj);
    lv_obj_set_grid_cell(bt_rt, LV_GRID_ALIGN_END, 2, 1,
                         LV_GRID_ALIGN_START, 0, 1);
    lv_obj_clear_flag(bt_rt, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(bt_rt, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *bt_rb = lv_btn_create(obj);
    lv_obj_set_grid_cell(bt_rb, LV_GRID_ALIGN_END, 2, 1,
                         LV_GRID_ALIGN_END, 2, 1);
    lv_obj_clear_flag(bt_rb, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(bt_rb, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * SCREEN_CALIBRATION_NUM);
    children[SCREEN_CALIBRATION_TIPS] = lable_obj;
    children[SCREEN_CALIBRATION_LT] = bt_lt;
    children[SCREEN_CALIBRATION_RT] = bt_lb;
    children[SCREEN_CALIBRATION_LB] = bt_rt;
    children[SCREEN_CALIBRATION_RT] = bt_rb;
    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    /** add event*/

    lv_obj_add_event_cb(obj, ui_calibration_all_event_cb, LV_EVENT_ALL, NULL);

    return obj;
}
