// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_P00startup.h"
#include "ui_comp.h"

lv_obj_t *ui_startup_create(lv_obj_t *parent)
{
    lv_obj_t *obj;
    lv_obj_t *obj_logo;
    lv_obj_t *obj_bar;
    obj = lv_obj_create(parent);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(obj, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(obj, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    obj_logo = lv_img_create(obj);
    lv_img_set_src(obj_logo, &ui_img_gltech_png);
    lv_obj_set_size(obj_logo, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(obj_logo, -3, -267);

    lv_obj_set_align(obj_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(obj_logo, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(obj_logo, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    obj_bar = lv_bar_create(obj);
    lv_bar_set_range(obj_bar, 0, 100);

    lv_obj_set_size(obj_bar, 312, 10);
    lv_obj_set_pos(obj_bar, 94, -18);
    lv_obj_set_align(obj_bar, LV_ALIGN_CENTER);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * SCREEN_P00_NUM);
    lv_memset_00(children, sizeof(lv_obj_t *) * SCREEN_P00_NUM);
    children[SCREEN_P00_LOGO] = obj_logo;
    children[SCREEN_P00_BAR] = obj_bar;
    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    /** add event*/
    void ui_startup_all_event_cb(lv_event_t * e);
    lv_obj_add_event_cb(obj, ui_startup_all_event_cb, LV_EVENT_ALL, NULL);

    return obj;
}
