// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_P00startup_screen_init(void)
{
    ui_P00startup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_P00startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo = lv_img_create(ui_P00startup);
    lv_img_set_src(ui_logo, &ui_img_logo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo, -3);
    lv_obj_set_y(ui_logo, -27);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_startBar = lv_bar_create(ui_P00startup);
    lv_bar_set_value(ui_startBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_startBar, 312);
    lv_obj_set_height(ui_startBar, 10);
    lv_obj_set_x(ui_startBar, -18);
    lv_obj_set_y(ui_startBar, 94);
    lv_obj_set_align(ui_startBar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_startBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_startBar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

}
