// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_P00startup.h"
#include "ui_comp.h"

typedef struct ui_P00startup_TIME
{

    lv_obj_t *screen;

} P00_time_t;
static lv_timer_t *timehandle;
void ui_P01main_screen_init(void);
static void time_cb(struct _lv_timer_t *timer)
{
    lv_obj_t *obj_bar = ui_comp_get_child(timer->user_data, COMP_P00_BAR);
    if (obj_bar)
    {
        int32_t min = lv_bar_get_min_value(obj_bar);
        int32_t max = lv_bar_get_max_value(obj_bar);
        int32_t cur = lv_bar_get_value(obj_bar);
        int32_t step = (max - min) / 50;
        if (cur >= max)
        {
            _ui_screen_change(&ui_P01main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 100, ui_P01main_screen_init);
        }
        lv_bar_set_value(obj_bar, cur + step, LV_ANIM_ON);
    }
}

void ui_startup_all_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (LV_EVENT_SCREEN_LOADED == code)
    {
        timehandle = lv_timer_create(time_cb, 50, obj);
    }
    else if (LV_EVENT_SCREEN_UNLOADED == code)
    {
        lv_timer_del(timehandle);
    }
}
