// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_SCREEN_P00_STARTUP_H
#define _UI_SCREEN_P00_STARTUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT P00_STARTUP
    enum UI_SCREEN_P00_STARTUP
    {
        SCREEN_P00_LOGO,
        SCREEN_P00_BAR,
        SCREEN_P00_NUM,
    };
    lv_obj_t *ui_startup_create(lv_obj_t *parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
