// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_comp.h"
#include "ui_P01main.h"
#include "ui_comp_statebar.h"
#include "ui_comp_titlebar.h"
#include "system_var.h"
#include "ui_comp_tabview_main.h"

static lv_obj_t *main;
lv_obj_t *ui_main_create(lv_obj_t *parent)
{
    static const lv_coord_t col_dsc[] = {LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static const lv_coord_t row_dsc[] = {LV_GRID_FR(10), LV_GRID_FR(80), LV_GRID_FR(8), LV_GRID_TEMPLATE_LAST};

    lv_obj_t *obj = NULL;
    obj = lv_obj_create(parent);
    main = obj;
    lv_obj_set_style_pad_top(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_grid_dsc_array(obj, col_dsc, row_dsc);
    lv_obj_center(obj);

    lv_obj_t *ui_head = ui_titleBar_create(obj);
    lv_obj_set_grid_cell(ui_head, LV_GRID_ALIGN_STRETCH, 0, 1,
                         LV_GRID_ALIGN_STRETCH, 0, 1);
    lv_event_send(ui_head, LV_EVENT_SET_TITLE, (void *)g_var_init.product_name);

    lv_obj_t *ui_TabView1 = ui_TabView_main_create(obj);
    lv_obj_set_grid_cell(ui_TabView1, LV_GRID_ALIGN_STRETCH, 0, 1,
                         LV_GRID_ALIGN_STRETCH, 1, 1);

    lv_obj_t *ui_stateBar = ui_stateBar_create(obj);
    lv_obj_set_grid_cell(ui_stateBar, LV_GRID_ALIGN_STRETCH, 0, 1,
                         LV_GRID_ALIGN_STRETCH, 2, 1);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * SCREEN_P01_NUM);
    lv_memset_00(children, sizeof(lv_obj_t *) * SCREEN_P01_NUM);
    children[SCREEN_P01_TITLE_BAR] = ui_head;
    children[SCREEN_P01_TABLE] = ui_TabView1;
    children[SCREEN_P01_STATE_BAR] = ui_stateBar;
    lv_obj_add_event_cb(obj, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(obj, del_component_child_event_cb, LV_EVENT_DELETE, children);

    return obj;
}

void main_update_tips(const char *string)
{
    lv_obj_t *statusBar_obj;
    if (main)
    {
        statusBar_obj = ui_comp_get_child(main, SCREEN_P01_STATE_BAR);
        stateBar_update_tips(statusBar_obj, string);
    }
}
