// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_P00startup.h"
#include "ui_comp.h"
#include "ui_P01main.h"

static void set_bar(void *bar, int32_t bar_value)
{
    lv_bar_set_value(bar, bar_value, LV_ANIM_ON);
    int32_t max = lv_bar_get_max_value(bar);
    if (bar_value == max)
    {
        //_ui_screen_change(&ui_P01main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 100, ui_P01main_screen_init);
        lv_scr_load_anim(ui_main_create(NULL), LV_SCR_LOAD_ANIM_FADE_ON, 300, 100, true); /*!< 切换页面并删除启动页 */
    }
}

void ui_startup_all_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (LV_EVENT_SCREEN_LOADED == code)
    {
        lv_obj_t *obj_bar = ui_comp_get_child(obj, SCREEN_P00_BAR);
        /*!< 进度条动画 */
        lv_anim_t a;
        lv_anim_init(&a);
        lv_anim_set_exec_cb(&a, set_bar);
        lv_anim_set_time(&a, 3000); /*!< 3000ms 动画时间 */
        lv_anim_set_var(&a, obj_bar);
        lv_anim_set_values(&a, 0, 100); /*!< 动画从0到100 */
        lv_anim_start(&a);
    }
    else if (LV_EVENT_SCREEN_UNLOADED == code)
    {
    }
}
