// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_P00startup_screen_init(void)
{
ui_P00startup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_P00startup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_P00startup,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_P00startup, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_P00startup, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_P00startup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_P00startup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_P00startup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_P00startup, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_P00startup, 40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_P00startup);
lv_img_set_src(ui_Image1, &ui_img_gltech_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, -3 );
lv_obj_set_y( ui_Image1, -267 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_startBar = lv_bar_create(ui_P00startup);
lv_bar_set_value(ui_startBar,25,LV_ANIM_OFF);
lv_obj_set_width( ui_startBar, 312);
lv_obj_set_height( ui_startBar, 10);
lv_obj_set_x( ui_startBar, -18 );
lv_obj_set_y( ui_startBar, 94 );
lv_obj_set_align( ui_startBar, LV_ALIGN_CENTER );


}
