// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_P01main_screen_init(void)
{
    ui_P01main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_P01main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_P01main, LV_DIR_LEFT, 50);
    lv_obj_set_width(ui_TabView1, 480);
    lv_obj_set_height(ui_TabView1, 200);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TabView1, &ui_font_heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "测量");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "系统");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "模块");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "高级");

    ui_TabPage5 = lv_tabview_add_tab(ui_TabView1, "关于");

}
