from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
src += Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('efsm', src, depend = ['remove'], CPPPATH = CPPPATH)

Return('group')
